spring:

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_library
    username: postgres
    password: postgres

  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect

  kafka:
    bootstrap-servers: http://localhost:9092
    consumer:
      group-id: book_addition-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  server:
    port: 8091

  url:
    library: ${LIBRARY_SERVICE_URL:http://localhost:8888/storage}

  topic:
    name: book.addition.id.notification